- name: "Add group {{ victoriametrics_agent_system_group }}"
  ansible.builtin.group:
    name: "{{ victoriametrics_agent_system_group }}"
    state: present

- name: "Add user {{ victoriametrics_agent_system_user }}"
  ansible.builtin.user:
    name: "{{ victoriametrics_agent_system_user }}"
    group: "{{ victoriametrics_agent_system_group }}"
    shell: "/bin/false"
    system: true
    create_home: false
    state: present

- name: "Create vmagent config folder"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "vmagent"
    group: "vmagent"
    mode: "0755"
  loop:
    - "{{ victoriametrics_agent_config_dir }}"
    - "{{ victoriametrics_agent_config_dir }}/conf"
    - "{{ victoriametrics_agent_data_dir }}"
    - "{{ victoriametrics_agent_data_dir }}/tmp"

- name: "Setup vmagent service"
  ansible.builtin.template:
    src: "vmagent.service.j2"
    dest: "/etc/systemd/system/vmagent.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Reload vmagent service"

- name: "Setup vmagent config"
  ansible.builtin.template:
    src: "vmagent.yml.j2"
    dest: "/etc/vmagent/vmagent.yml"
    owner: "vmagent"
    group: "vmagent"
    mode: "0644"
  notify: "Reload vmagent service"

- name: "Ensure vmagent service is started and enabled"
  ansible.builtin.systemd:
    daemon_reload: true
    state: started
    enabled: true
    name: "vmagent"
  notify: "Reload vmagent service"
