- name: "Create folder {{ _victoriametrics_tmp_folder }}"
  ansible.builtin.file:
    path: "{{ _victoriametrics_tmp_folder }}"
    state: directory
    mode: "0755"

- name: "Download victoriametrics utils to tmp folder"
  ansible.builtin.get_url:
    url: "{{ victoriametrics_utils_download_url }}"
    dest: "{{ _victoriametrics_tmp_tarball }}"
    mode: "0755"

- name: "Extract victoriametrics utils to tmp"
  ansible.builtin.unarchive:
    src: "{{ _victoriametrics_tmp_tarball }}"
    dest: "{{ _victoriametrics_tmp_folder }}"
    remote_src: true
    mode: "0755"
