- name: "Check if service is present"
  ansible.builtin.stat:
    path: "/etc/systemd/system/vmagent.service"
  register: _vmu_service_stat

- name: "Check if config is present"
  ansible.builtin.stat:
    path: "{{ victoriametrics_agent_config_dir }}/vmagent.yml"
  register: _vmu_config_stat

- name: "Reload service"
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "vmagent"
  when: _vmu_service_stat.stat.exists and _vmu_config_stat.stat.exists
