- name: "Include preflight tasks"
  ansible.builtin.include_tasks: "preflight.yml"

- name: "Include install tasks for utils requested"
  ansible.builtin.include_tasks: "install_bin.yml"
  vars:
    _vmu_bin: "{{ item }}"
  loop: "{{ victoriametrics_utils_install }}"

- name: "Configure vmagent service and config"
  ansible.builtin.include_tasks: "config_vmagent.yml"
  when: "'vmagent' in victoriametrics_utils_install"

- name: "Configure vmauth service and config"
  ansible.builtin.include_tasks: "config_vmauth.yml"
  when: "'vmauth' in victoriametrics_utils_install"

- name: "Cleanup tmp files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ _victoriametrics_tmp_tarball }}"
    - "{{ _victoriametrics_tmp_folder }}"
