---
# handlers file for msterhuj.victoriametrics_utils
- name: "Reload vmagent service"
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: vmagent

- name: "Reload vmauth service"
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: vmauth
